name: Smart Contract CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Hardhat Tests
        run: npx hardhat test
        
- name: Start Prometheus for Monitoring
  run: docker run -d -p 9090:9090 prom/prometheus
  
- name: Deploy to Kubernetes via ArgoCD
  run: argocd app sync my-contract-app

  ```yaml
   deploy:
     runs-on: ubuntu-latest
     needs: [build]
     if: github.ref == 'refs/heads/main'

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Install Hardhat
         run: npm install

       - name: Deploy to Goerli Testnet
         env:
           INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
         run: npx hardhat run scripts/deploy.js --network goerli

       - name: Verify Contract on Etherscan
         env:
           ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
         run: npx hardhat verify --network goerli DEPLOYED_CONTRACT_ADDRESS
